# Data path. adjust them!
common:
    image_file: "/home/data/left_wcam/distorted/000001662130.png"
    pcd_file: "/home/data/dcam/pointcloud/000001662130.pcd"
    result_file: "/home/data/extrinsic_result.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [582.12511985, 0.0,      507.5,
                    0.0,     582.12511985,  507.5,
                    0.0,     0.0,      1.0     ]
    # 6 dist coeffs in format radial [k1,k2,k3,k4], tangential [p1, p2]
    dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/catkin_ws/src/livox_camera_calib/config/config_mlr.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
